services:
  app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
       - POSTGRES_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_CONTAINER_NAME}:5432/${POSTGRES_DB}
       - FILE_SIZE_LIMIT=${FILE_SIZE_LIMIT}
    links:
      - postgres
    ports:
      - '5000:5000'
    restart: unless-stopped
    stop_signal: SIGKILL

  postgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./db/:/var/lib/postgresql/data